### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by akang-ai** [LiamLian0727/USIS10K#11]
Traceback (most recent call last):
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'home/LYK/usis10k/sam-vit-huge'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/LYK/usis10k/tools/train.py", line 125, in <module>
    main()
  File "/home/LYK/usis10k/tools/train.py", line 114, in main
    runner = Runner.from_cfg(cfg)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/LYK/usis10k/project/our/our_model/anchor.py", line 38, in __init__
    super().__init__(*args, **kwargs)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmdet/models/detectors/mask_rcnn.py", line 22, in __init__
    super().__init__(
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmdet/models/detectors/two_stage.py", line 34, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/LYK/usis10k/project/our/our_model/common.py", line 180, in __init__
    sam_config = SamConfig.from_pretrained(hf_pretrain_name).vision_config
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/transformers/configuration_utils.py", line 545, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/transformers/configuration_utils.py", line 633, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/LYK/anaconda3/envs/test/lib/python3.9/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'home/LYK/usis10k/sam-vit-huge'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
请问我该如何修改路径
![image](https://github.com/user-attachments/assets/14b440ea-6d62-45f4-911d-2c12f84a4f79)

**Comment by LiamLian0727** [comment]
You need to first download the sam huge weights by referring to the following in the readme, then change the path in the config to your own
![image](https://github.com/user-attachments/assets/d74441e5-43c3-44f3-9d27-c2f87cb4c7dc)
Or you can refer to the corresponding tutorial in the `huggingface-cli` command to manually modify the part of the source code that loads the huggingface model

**Comment by akang-ai** [comment]
![image](https://github.com/user-attachments/assets/121b0ffb-3133-417d-b48a-9b7ae582b3c5)
你我已经下载到本地了，还是会出现路径报错

**Comment by akang-ai** [comment]
![image](https://github.com/user-attachments/assets/f2a2ea51-6684-4081-aad6-8548fed30b6e)
![image](https://github.com/user-attachments/assets/8a280cdb-38b3-403e-97aa-2db16fd4787e)
我刚刚用你提供的代码下载好了，但还是出现这个问题

**Comment by LiamLian0727** [comment]
It seems that this is a bug caused by the huggingface api and not our code, you can either check your version of huggingface, ask for help in the huggingface community, or manually modify the part of our model that loads the weights of the huggingface model to help the huggingface api to be correct find the SAM-Huge weights file.
